language: r
cache: packages
sudo: false

before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get install r-cran-rjags

notifications:
  email:
    on_success: change
    on_failure: change
